url: http://targence.github.io/zh
description: site description
title: 差不多
author: Alex

limit_posts: 0
show_drafts: null

markdown_ext: "markdown,mkdown,mkdn,mkd,md"

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
